# .goreleaser.yaml
snapshot:
  # Allows you to change the name of the generated snapshot
  #
  # Note that some pipes require this to be semantic version compliant (nfpm,
  # for example).
  #
  # Default: `{{ .Version }}-SNAPSHOT-{{.ShortCommit}}`.
  # Templates: allowed.
  version_template: "{{ incpatch .Version }}-devel"