// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: honeypot.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Greeter_SayHello_FullMethodName = "/honeypot.Greeter/SayHello"
)

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, Greeter_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility.
//
// The greeting service definition.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreeterServer struct{}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}
func (UnimplementedGreeterServer) testEmbeddedByValue()                 {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	// If the following call pancis, it indicates UnimplementedGreeterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Greeter_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "honeypot.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "honeypot.proto",
}

const (
	Honeypot_Connect_FullMethodName              = "/honeypot.Honeypot/Connect"
	Honeypot_SaveFtpLogin_FullMethodName         = "/honeypot.Honeypot/SaveFtpLogin"
	Honeypot_SaveElasticsearch_FullMethodName    = "/honeypot.Honeypot/SaveElasticsearch"
	Honeypot_SaveHttp_FullMethodName             = "/honeypot.Honeypot/SaveHttp"
	Honeypot_SaveSshLogin_FullMethodName         = "/honeypot.Honeypot/SaveSshLogin"
	Honeypot_SavePostgresLogin_FullMethodName    = "/honeypot.Honeypot/SavePostgresLogin"
	Honeypot_SaveMysqlLogin_FullMethodName       = "/honeypot.Honeypot/SaveMysqlLogin"
	Honeypot_SaveQuery_FullMethodName            = "/honeypot.Honeypot/SaveQuery"
	Honeypot_SaveHttpHeaders_FullMethodName      = "/honeypot.Honeypot/SaveHttpHeaders"
	Honeypot_SaveShellCommand_FullMethodName     = "/honeypot.Honeypot/SaveShellCommand"
	Honeypot_GetCommandResponse_FullMethodName   = "/honeypot.Honeypot/GetCommandResponse"
	Honeypot_SaveOpenclawConnect_FullMethodName  = "/honeypot.Honeypot/SaveOpenclawConnect"
	Honeypot_SaveKafkaConnect_FullMethodName     = "/honeypot.Honeypot/SaveKafkaConnect"
	Honeypot_SaveKafkaApiRequest_FullMethodName  = "/honeypot.Honeypot/SaveKafkaApiRequest"
	Honeypot_SaveRedisConnect_FullMethodName     = "/honeypot.Honeypot/SaveRedisConnect"
	Honeypot_SaveRedisCommand_FullMethodName     = "/honeypot.Honeypot/SaveRedisCommand"
	Honeypot_SaveDockerRequest_FullMethodName    = "/honeypot.Honeypot/SaveDockerRequest"
	Honeypot_SaveMongoConnect_FullMethodName     = "/honeypot.Honeypot/SaveMongoConnect"
	Honeypot_SaveMongoCommand_FullMethodName     = "/honeypot.Honeypot/SaveMongoCommand"
	Honeypot_SaveMemcachedConnect_FullMethodName = "/honeypot.Honeypot/SaveMemcachedConnect"
	Honeypot_SaveMemcachedCommand_FullMethodName = "/honeypot.Honeypot/SaveMemcachedCommand"
	Honeypot_SaveEtcdRequest_FullMethodName      = "/honeypot.Honeypot/SaveEtcdRequest"
	Honeypot_SaveSmbConnect_FullMethodName       = "/honeypot.Honeypot/SaveSmbConnect"
	Honeypot_SaveLdapBind_FullMethodName         = "/honeypot.Honeypot/SaveLdapBind"
	Honeypot_SaveLdapSearch_FullMethodName       = "/honeypot.Honeypot/SaveLdapSearch"
	Honeypot_SaveTelnetLogin_FullMethodName      = "/honeypot.Honeypot/SaveTelnetLogin"
	Honeypot_SaveTelnetCommand_FullMethodName    = "/honeypot.Honeypot/SaveTelnetCommand"
	Honeypot_SaveRdpConnect_FullMethodName       = "/honeypot.Honeypot/SaveRdpConnect"
	Honeypot_SaveVncConnect_FullMethodName       = "/honeypot.Honeypot/SaveVncConnect"
)

// HoneypotClient is the client API for Honeypot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HoneypotClient interface {
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error)
	SaveFtpLogin(ctx context.Context, in *FtpRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveElasticsearch(ctx context.Context, in *ElasticsearchRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveHttp(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveSshLogin(ctx context.Context, in *SshLoginRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SavePostgresLogin(ctx context.Context, in *PostgresRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveMysqlLogin(ctx context.Context, in *MysqlRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveHttpHeaders(ctx context.Context, in *HttpHeaderRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveShellCommand(ctx context.Context, in *ShellCommandRequest, opts ...grpc.CallOption) (*SaveReply, error)
	GetCommandResponse(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	SaveOpenclawConnect(ctx context.Context, in *OpenclawRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveKafkaConnect(ctx context.Context, in *KafkaRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveKafkaApiRequest(ctx context.Context, in *KafkaApiRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveRedisConnect(ctx context.Context, in *RedisConnectRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveRedisCommand(ctx context.Context, in *RedisCommandRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveDockerRequest(ctx context.Context, in *DockerRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveMongoConnect(ctx context.Context, in *MongoConnectRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveMongoCommand(ctx context.Context, in *MongoCommandRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveMemcachedConnect(ctx context.Context, in *MemcachedConnectRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveMemcachedCommand(ctx context.Context, in *MemcachedCommandRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveEtcdRequest(ctx context.Context, in *EtcdRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveSmbConnect(ctx context.Context, in *SmbRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveLdapBind(ctx context.Context, in *LdapBindRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveLdapSearch(ctx context.Context, in *LdapSearchRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveTelnetLogin(ctx context.Context, in *TelnetLoginRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveTelnetCommand(ctx context.Context, in *TelnetCommandRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveRdpConnect(ctx context.Context, in *RdpRequest, opts ...grpc.CallOption) (*SaveReply, error)
	SaveVncConnect(ctx context.Context, in *VncRequest, opts ...grpc.CallOption) (*SaveReply, error)
}

type honeypotClient struct {
	cc grpc.ClientConnInterface
}

func NewHoneypotClient(cc grpc.ClientConnInterface) HoneypotClient {
	return &honeypotClient{cc}
}

func (c *honeypotClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectReply)
	err := c.cc.Invoke(ctx, Honeypot_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveFtpLogin(ctx context.Context, in *FtpRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveFtpLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveElasticsearch(ctx context.Context, in *ElasticsearchRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveElasticsearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveHttp(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveHttp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveSshLogin(ctx context.Context, in *SshLoginRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveSshLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SavePostgresLogin(ctx context.Context, in *PostgresRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SavePostgresLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveMysqlLogin(ctx context.Context, in *MysqlRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveMysqlLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveHttpHeaders(ctx context.Context, in *HttpHeaderRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveHttpHeaders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveShellCommand(ctx context.Context, in *ShellCommandRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveShellCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) GetCommandResponse(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, Honeypot_GetCommandResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveOpenclawConnect(ctx context.Context, in *OpenclawRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveOpenclawConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveKafkaConnect(ctx context.Context, in *KafkaRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveKafkaConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveKafkaApiRequest(ctx context.Context, in *KafkaApiRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveKafkaApiRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveRedisConnect(ctx context.Context, in *RedisConnectRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveRedisConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveRedisCommand(ctx context.Context, in *RedisCommandRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveRedisCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveDockerRequest(ctx context.Context, in *DockerRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveDockerRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveMongoConnect(ctx context.Context, in *MongoConnectRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveMongoConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveMongoCommand(ctx context.Context, in *MongoCommandRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveMongoCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveMemcachedConnect(ctx context.Context, in *MemcachedConnectRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveMemcachedConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveMemcachedCommand(ctx context.Context, in *MemcachedCommandRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveMemcachedCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveEtcdRequest(ctx context.Context, in *EtcdRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveEtcdRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveSmbConnect(ctx context.Context, in *SmbRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveSmbConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveLdapBind(ctx context.Context, in *LdapBindRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveLdapBind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveLdapSearch(ctx context.Context, in *LdapSearchRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveLdapSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveTelnetLogin(ctx context.Context, in *TelnetLoginRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveTelnetLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveTelnetCommand(ctx context.Context, in *TelnetCommandRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveTelnetCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveRdpConnect(ctx context.Context, in *RdpRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveRdpConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *honeypotClient) SaveVncConnect(ctx context.Context, in *VncRequest, opts ...grpc.CallOption) (*SaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, Honeypot_SaveVncConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HoneypotServer is the server API for Honeypot service.
// All implementations must embed UnimplementedHoneypotServer
// for forward compatibility.
type HoneypotServer interface {
	Connect(context.Context, *ConnectRequest) (*ConnectReply, error)
	SaveFtpLogin(context.Context, *FtpRequest) (*SaveReply, error)
	SaveElasticsearch(context.Context, *ElasticsearchRequest) (*SaveReply, error)
	SaveHttp(context.Context, *HttpRequest) (*SaveReply, error)
	SaveSshLogin(context.Context, *SshLoginRequest) (*SaveReply, error)
	SavePostgresLogin(context.Context, *PostgresRequest) (*SaveReply, error)
	SaveMysqlLogin(context.Context, *MysqlRequest) (*SaveReply, error)
	SaveQuery(context.Context, *QueryRequest) (*SaveReply, error)
	SaveHttpHeaders(context.Context, *HttpHeaderRequest) (*SaveReply, error)
	SaveShellCommand(context.Context, *ShellCommandRequest) (*SaveReply, error)
	GetCommandResponse(context.Context, *CommandRequest) (*CommandResponse, error)
	SaveOpenclawConnect(context.Context, *OpenclawRequest) (*SaveReply, error)
	SaveKafkaConnect(context.Context, *KafkaRequest) (*SaveReply, error)
	SaveKafkaApiRequest(context.Context, *KafkaApiRequest) (*SaveReply, error)
	SaveRedisConnect(context.Context, *RedisConnectRequest) (*SaveReply, error)
	SaveRedisCommand(context.Context, *RedisCommandRequest) (*SaveReply, error)
	SaveDockerRequest(context.Context, *DockerRequest) (*SaveReply, error)
	SaveMongoConnect(context.Context, *MongoConnectRequest) (*SaveReply, error)
	SaveMongoCommand(context.Context, *MongoCommandRequest) (*SaveReply, error)
	SaveMemcachedConnect(context.Context, *MemcachedConnectRequest) (*SaveReply, error)
	SaveMemcachedCommand(context.Context, *MemcachedCommandRequest) (*SaveReply, error)
	SaveEtcdRequest(context.Context, *EtcdRequest) (*SaveReply, error)
	SaveSmbConnect(context.Context, *SmbRequest) (*SaveReply, error)
	SaveLdapBind(context.Context, *LdapBindRequest) (*SaveReply, error)
	SaveLdapSearch(context.Context, *LdapSearchRequest) (*SaveReply, error)
	SaveTelnetLogin(context.Context, *TelnetLoginRequest) (*SaveReply, error)
	SaveTelnetCommand(context.Context, *TelnetCommandRequest) (*SaveReply, error)
	SaveRdpConnect(context.Context, *RdpRequest) (*SaveReply, error)
	SaveVncConnect(context.Context, *VncRequest) (*SaveReply, error)
	mustEmbedUnimplementedHoneypotServer()
}

// UnimplementedHoneypotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHoneypotServer struct{}

func (UnimplementedHoneypotServer) Connect(context.Context, *ConnectRequest) (*ConnectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedHoneypotServer) SaveFtpLogin(context.Context, *FtpRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveFtpLogin not implemented")
}
func (UnimplementedHoneypotServer) SaveElasticsearch(context.Context, *ElasticsearchRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveElasticsearch not implemented")
}
func (UnimplementedHoneypotServer) SaveHttp(context.Context, *HttpRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveHttp not implemented")
}
func (UnimplementedHoneypotServer) SaveSshLogin(context.Context, *SshLoginRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSshLogin not implemented")
}
func (UnimplementedHoneypotServer) SavePostgresLogin(context.Context, *PostgresRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SavePostgresLogin not implemented")
}
func (UnimplementedHoneypotServer) SaveMysqlLogin(context.Context, *MysqlRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMysqlLogin not implemented")
}
func (UnimplementedHoneypotServer) SaveQuery(context.Context, *QueryRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveQuery not implemented")
}
func (UnimplementedHoneypotServer) SaveHttpHeaders(context.Context, *HttpHeaderRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveHttpHeaders not implemented")
}
func (UnimplementedHoneypotServer) SaveShellCommand(context.Context, *ShellCommandRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveShellCommand not implemented")
}
func (UnimplementedHoneypotServer) GetCommandResponse(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommandResponse not implemented")
}
func (UnimplementedHoneypotServer) SaveOpenclawConnect(context.Context, *OpenclawRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOpenclawConnect not implemented")
}
func (UnimplementedHoneypotServer) SaveKafkaConnect(context.Context, *KafkaRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveKafkaConnect not implemented")
}
func (UnimplementedHoneypotServer) SaveKafkaApiRequest(context.Context, *KafkaApiRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveKafkaApiRequest not implemented")
}
func (UnimplementedHoneypotServer) SaveRedisConnect(context.Context, *RedisConnectRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRedisConnect not implemented")
}
func (UnimplementedHoneypotServer) SaveRedisCommand(context.Context, *RedisCommandRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRedisCommand not implemented")
}
func (UnimplementedHoneypotServer) SaveDockerRequest(context.Context, *DockerRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveDockerRequest not implemented")
}
func (UnimplementedHoneypotServer) SaveMongoConnect(context.Context, *MongoConnectRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMongoConnect not implemented")
}
func (UnimplementedHoneypotServer) SaveMongoCommand(context.Context, *MongoCommandRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMongoCommand not implemented")
}
func (UnimplementedHoneypotServer) SaveMemcachedConnect(context.Context, *MemcachedConnectRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMemcachedConnect not implemented")
}
func (UnimplementedHoneypotServer) SaveMemcachedCommand(context.Context, *MemcachedCommandRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveMemcachedCommand not implemented")
}
func (UnimplementedHoneypotServer) SaveEtcdRequest(context.Context, *EtcdRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveEtcdRequest not implemented")
}
func (UnimplementedHoneypotServer) SaveSmbConnect(context.Context, *SmbRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSmbConnect not implemented")
}
func (UnimplementedHoneypotServer) SaveLdapBind(context.Context, *LdapBindRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveLdapBind not implemented")
}
func (UnimplementedHoneypotServer) SaveLdapSearch(context.Context, *LdapSearchRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveLdapSearch not implemented")
}
func (UnimplementedHoneypotServer) SaveTelnetLogin(context.Context, *TelnetLoginRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTelnetLogin not implemented")
}
func (UnimplementedHoneypotServer) SaveTelnetCommand(context.Context, *TelnetCommandRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTelnetCommand not implemented")
}
func (UnimplementedHoneypotServer) SaveRdpConnect(context.Context, *RdpRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveRdpConnect not implemented")
}
func (UnimplementedHoneypotServer) SaveVncConnect(context.Context, *VncRequest) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveVncConnect not implemented")
}
func (UnimplementedHoneypotServer) mustEmbedUnimplementedHoneypotServer() {}
func (UnimplementedHoneypotServer) testEmbeddedByValue()                  {}

// UnsafeHoneypotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HoneypotServer will
// result in compilation errors.
type UnsafeHoneypotServer interface {
	mustEmbedUnimplementedHoneypotServer()
}

func RegisterHoneypotServer(s grpc.ServiceRegistrar, srv HoneypotServer) {
	// If the following call pancis, it indicates UnimplementedHoneypotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Honeypot_ServiceDesc, srv)
}

func _Honeypot_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveFtpLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveFtpLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveFtpLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveFtpLogin(ctx, req.(*FtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveElasticsearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElasticsearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveElasticsearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveElasticsearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveElasticsearch(ctx, req.(*ElasticsearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveHttp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveHttp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveHttp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveHttp(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveSshLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SshLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveSshLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveSshLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveSshLogin(ctx, req.(*SshLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SavePostgresLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostgresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SavePostgresLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SavePostgresLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SavePostgresLogin(ctx, req.(*PostgresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveMysqlLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MysqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveMysqlLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveMysqlLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveMysqlLogin(ctx, req.(*MysqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveQuery(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveHttpHeaders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpHeaderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveHttpHeaders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveHttpHeaders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveHttpHeaders(ctx, req.(*HttpHeaderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveShellCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShellCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveShellCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveShellCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveShellCommand(ctx, req.(*ShellCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_GetCommandResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).GetCommandResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_GetCommandResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).GetCommandResponse(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveOpenclawConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenclawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveOpenclawConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveOpenclawConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveOpenclawConnect(ctx, req.(*OpenclawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveKafkaConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KafkaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveKafkaConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveKafkaConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveKafkaConnect(ctx, req.(*KafkaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveKafkaApiRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KafkaApiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveKafkaApiRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveKafkaApiRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveKafkaApiRequest(ctx, req.(*KafkaApiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveRedisConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveRedisConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveRedisConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveRedisConnect(ctx, req.(*RedisConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveRedisCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveRedisCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveRedisCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveRedisCommand(ctx, req.(*RedisCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveDockerRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DockerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveDockerRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveDockerRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveDockerRequest(ctx, req.(*DockerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveMongoConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MongoConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveMongoConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveMongoConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveMongoConnect(ctx, req.(*MongoConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveMongoCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MongoCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveMongoCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveMongoCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveMongoCommand(ctx, req.(*MongoCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveMemcachedConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemcachedConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveMemcachedConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveMemcachedConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveMemcachedConnect(ctx, req.(*MemcachedConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveMemcachedCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemcachedCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveMemcachedCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveMemcachedCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveMemcachedCommand(ctx, req.(*MemcachedCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveEtcdRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EtcdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveEtcdRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveEtcdRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveEtcdRequest(ctx, req.(*EtcdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveSmbConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmbRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveSmbConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveSmbConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveSmbConnect(ctx, req.(*SmbRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveLdapBind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LdapBindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveLdapBind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveLdapBind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveLdapBind(ctx, req.(*LdapBindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveLdapSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LdapSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveLdapSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveLdapSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveLdapSearch(ctx, req.(*LdapSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveTelnetLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelnetLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveTelnetLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveTelnetLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveTelnetLogin(ctx, req.(*TelnetLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveTelnetCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelnetCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveTelnetCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveTelnetCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveTelnetCommand(ctx, req.(*TelnetCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveRdpConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RdpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveRdpConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveRdpConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveRdpConnect(ctx, req.(*RdpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Honeypot_SaveVncConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HoneypotServer).SaveVncConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Honeypot_SaveVncConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HoneypotServer).SaveVncConnect(ctx, req.(*VncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Honeypot_ServiceDesc is the grpc.ServiceDesc for Honeypot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Honeypot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "honeypot.Honeypot",
	HandlerType: (*HoneypotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Honeypot_Connect_Handler,
		},
		{
			MethodName: "SaveFtpLogin",
			Handler:    _Honeypot_SaveFtpLogin_Handler,
		},
		{
			MethodName: "SaveElasticsearch",
			Handler:    _Honeypot_SaveElasticsearch_Handler,
		},
		{
			MethodName: "SaveHttp",
			Handler:    _Honeypot_SaveHttp_Handler,
		},
		{
			MethodName: "SaveSshLogin",
			Handler:    _Honeypot_SaveSshLogin_Handler,
		},
		{
			MethodName: "SavePostgresLogin",
			Handler:    _Honeypot_SavePostgresLogin_Handler,
		},
		{
			MethodName: "SaveMysqlLogin",
			Handler:    _Honeypot_SaveMysqlLogin_Handler,
		},
		{
			MethodName: "SaveQuery",
			Handler:    _Honeypot_SaveQuery_Handler,
		},
		{
			MethodName: "SaveHttpHeaders",
			Handler:    _Honeypot_SaveHttpHeaders_Handler,
		},
		{
			MethodName: "SaveShellCommand",
			Handler:    _Honeypot_SaveShellCommand_Handler,
		},
		{
			MethodName: "GetCommandResponse",
			Handler:    _Honeypot_GetCommandResponse_Handler,
		},
		{
			MethodName: "SaveOpenclawConnect",
			Handler:    _Honeypot_SaveOpenclawConnect_Handler,
		},
		{
			MethodName: "SaveKafkaConnect",
			Handler:    _Honeypot_SaveKafkaConnect_Handler,
		},
		{
			MethodName: "SaveKafkaApiRequest",
			Handler:    _Honeypot_SaveKafkaApiRequest_Handler,
		},
		{
			MethodName: "SaveRedisConnect",
			Handler:    _Honeypot_SaveRedisConnect_Handler,
		},
		{
			MethodName: "SaveRedisCommand",
			Handler:    _Honeypot_SaveRedisCommand_Handler,
		},
		{
			MethodName: "SaveDockerRequest",
			Handler:    _Honeypot_SaveDockerRequest_Handler,
		},
		{
			MethodName: "SaveMongoConnect",
			Handler:    _Honeypot_SaveMongoConnect_Handler,
		},
		{
			MethodName: "SaveMongoCommand",
			Handler:    _Honeypot_SaveMongoCommand_Handler,
		},
		{
			MethodName: "SaveMemcachedConnect",
			Handler:    _Honeypot_SaveMemcachedConnect_Handler,
		},
		{
			MethodName: "SaveMemcachedCommand",
			Handler:    _Honeypot_SaveMemcachedCommand_Handler,
		},
		{
			MethodName: "SaveEtcdRequest",
			Handler:    _Honeypot_SaveEtcdRequest_Handler,
		},
		{
			MethodName: "SaveSmbConnect",
			Handler:    _Honeypot_SaveSmbConnect_Handler,
		},
		{
			MethodName: "SaveLdapBind",
			Handler:    _Honeypot_SaveLdapBind_Handler,
		},
		{
			MethodName: "SaveLdapSearch",
			Handler:    _Honeypot_SaveLdapSearch_Handler,
		},
		{
			MethodName: "SaveTelnetLogin",
			Handler:    _Honeypot_SaveTelnetLogin_Handler,
		},
		{
			MethodName: "SaveTelnetCommand",
			Handler:    _Honeypot_SaveTelnetCommand_Handler,
		},
		{
			MethodName: "SaveRdpConnect",
			Handler:    _Honeypot_SaveRdpConnect_Handler,
		},
		{
			MethodName: "SaveVncConnect",
			Handler:    _Honeypot_SaveVncConnect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "honeypot.proto",
}
