package ollama

import (
	"fmt"
	"net/http"
	"os"

	"github.com/gorilla/mux"
	"github.com/joshrendek/threat.gg-agent/cmdresp"
	"github.com/joshrendek/threat.gg-agent/honeypots"
	"github.com/joshrendek/threat.gg-agent/llmcore"
	"github.com/joshrendek/threat.gg-agent/persistence"
	"github.com/rs/zerolog"
)

const (
	defaultPort  = "11434"
	defaultModel = "llama3.2:latest"
)

var _ honeypots.Honeypot = &honeypot{}
var saveOllamaRequest = persistence.SaveOllamaRequest

type honeypot struct{ logger zerolog.Logger }

func New() honeypots.Honeypot {
	return &honeypot{logger: zerolog.New(os.Stdout).With().Caller().Str("honeypot", "ollama").Logger()}
}

func (h *honeypot) Name() string { return "ollama" }

func (h *honeypot) Start() {
	port := os.Getenv("OLLAMA_HONEYPOT_PORT")
	if port == "" {
		port = defaultPort
	}
	h.logger.Info().Str("port", port).Msg("starting ollama honeypot")
	h.logger.Fatal().Err(http.ListenAndServe(fmt.Sprintf(":%s", port), buildHandler())).Msg("failed to start")
}

// buildHandler composes the full chain; identityHeaders wraps cmdresp so the Server
// header is stamped even when an authored override short-circuits the router.
func buildHandler() http.Handler {
	return llmcore.Capture(saveOllamaRequest)(identityHeaders(cmdresp.MuxMiddleware("ollama")(newRouter())))
}

func identityHeaders(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Server", "Ollama")
		next.ServeHTTP(w, r)
	})
}

func newRouter() http.Handler {
	r := mux.NewRouter()
	r.HandleFunc("/", handleRoot).Methods("GET")
	r.HandleFunc("/api/tags", handleTags).Methods("GET")
	r.HandleFunc("/api/version", handleVersion).Methods("GET")
	r.HandleFunc("/api/ps", handlePs).Methods("GET")
	r.HandleFunc("/api/generate", func(w http.ResponseWriter, req *http.Request) {
		llmcore.OllamaGenerate(w, req, defaultModel)
	}).Methods("POST")
	r.HandleFunc("/api/chat", func(w http.ResponseWriter, req *http.Request) {
		llmcore.OllamaChat(w, req, defaultModel)
	}).Methods("POST")
	r.HandleFunc("/api/show", handleShow).Methods("POST")
	// OpenAI-compatible aliases
	r.HandleFunc("/v1/models", handleV1Models).Methods("GET")
	r.HandleFunc("/v1/chat/completions", func(w http.ResponseWriter, req *http.Request) {
		llmcore.ChatCompletion(w, req, defaultModel)
	}).Methods("POST")
	r.PathPrefix("/").HandlerFunc(handleCatchAll)
	return r
}

func handleRoot(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	fmt.Fprint(w, "Ollama is running")
}

func handleTags(w http.ResponseWriter, r *http.Request) {
	llmcore.WriteJSON(w, http.StatusOK, map[string]any{
		"models": []map[string]any{
			{
				"name": "llama3.2:latest", "model": "llama3.2:latest",
				"modified_at": "2026-06-01T12:00:00Z", "size": 2019393189,
				"digest":  "a80c4f17acd55265feb1f6c8f10a0b2b6b6c7f8a9b0c1d2e3f4a5b6c7d8e9f0a1",
				"details": map[string]any{"family": "llama", "parameter_size": "3.2B", "quantization_level": "Q4_K_M"},
			},
			{
				"name": "mistral:latest", "model": "mistral:latest",
				"modified_at": "2026-05-15T09:30:00Z", "size": 4113301824,
				"digest":  "61e88e884507ba5e06c49b40e6226884b2a16e872382c2b44a42f2d119d804a5",
				"details": map[string]any{"family": "llama", "parameter_size": "7B", "quantization_level": "Q4_0"},
			},
		},
	})
}

func handleVersion(w http.ResponseWriter, r *http.Request) {
	llmcore.WriteJSON(w, http.StatusOK, map[string]any{"version": "0.3.12"})
}

func handlePs(w http.ResponseWriter, r *http.Request) {
	llmcore.WriteJSON(w, http.StatusOK, map[string]any{"models": []any{}})
}

func handleShow(w http.ResponseWriter, r *http.Request) {
	llmcore.WriteJSON(w, http.StatusOK, map[string]any{
		"license":    "MIT",
		"modelfile":  "# Modelfile generated by \"ollama show\"\nFROM llama3.2",
		"parameters": "stop \"<|start_header_id|>\"",
		"template":   "{{ .System }}{{ .Prompt }}",
		"details":    map[string]any{"family": "llama", "parameter_size": "3.2B", "quantization_level": "Q4_K_M"},
	})
}

func handleV1Models(w http.ResponseWriter, r *http.Request) {
	llmcore.WriteJSON(w, http.StatusOK, map[string]any{
		"object": "list",
		"data": []map[string]any{
			{"id": "llama3.2:latest", "object": "model", "created": 1735689600, "owned_by": "library"},
			{"id": "mistral:latest", "object": "model", "created": 1735689600, "owned_by": "library"},
		},
	})
}

func handleCatchAll(w http.ResponseWriter, r *http.Request) {
	llmcore.WriteJSON(w, http.StatusNotFound, map[string]any{"error": "not found"})
}
