name: releaser

on:
  pull_request:
  push:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Calver Release
        uses: joshrendek/actions-calver@master
        id: calver
        with:
          date_format: "%Y-%m-%d"
          release_branch: 'v2'
          release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        env:
          VERSION: ${{ steps.calver.outputs.release }}
        run: ./deploy ${VERSION}
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      -
#        name: Set up Go
#        uses: actions/setup-go@v5
#      -
#        name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v6
#        with:
#          # either 'goreleaser' (default) or 'goreleaser-pro'
#          distribution: goreleaser
#          # 'latest', 'nightly', or a semver
#          version: '~> v2'
#          args: release --clean --snapshot
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
#          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
